dataset:
  dataset-name: lap14 # lap14, res14, res15, res16
  batch-size: 32
  shuffle-seed: null
sentence:
  max-length: 100
task:
  type: pair  # pair or triplet
encoder:
  type: glove-fasttext  # bert or glove-fasttext or indexer
  embedding_dimension: 400
  bert:
    source: bert-base-uncased
  glove-fasttext:
    fasttext-model: model_lap14.bin # in datasets/datasets/embeddings_data
    glove-file: gen.vec.npy # in datasets/datasets/embeddings_data
    indexer-path: word_idx.json # in datasets/datasets/embeddings_data
  indexer:
    word-to-idx: word_idx.json # in datasets/datasets/embeddings_data