dataset:
  dataset-name: lap14 # lap14, res14, res15, res16
  batch-size: 32
  shuffle-seed: null
sentence:
  max-length: 100
task:
  type: pair  # pair or triplet
encoder:
  type: glove-fasttext  # bert or glove-fasttext
  bert:
    source: bert-base-uncased
  glove-fasttext:
    word-to-idx: word_idx.json